# Change these first
owner: sider2vf # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: IMGUGU Home
    url: https://www.imgugu.ink/
  - name: Gugu's Blog
    url: https://blog.imgugu.ink/
  - name: Pigeon IT Access (SSO)
    url: https://sso.imgugu.ink/
  - name: Anime Pic
    url: https://moe.imgugu.ink/
  - name: IMGUGU Music
    url: https://music.imgugu.ink/
  - name: Pigeon SNS Web
    url: https://gpg.ink/
  - name: Pigeon SNS API Endpoint
    url: https://gpg.ink/api/v1/instance/
  - name: Pigeon SNS Object Storage
    url: https://mcdn.gpg.ink/
    expectedStatusCodes:
      - 403

status-website:
  # Add your custom domain name, or remove the cname line if you don't have a domain
  # Uncomment the baseUrl line if you don't have a custom domain and add your repo name there
  cname: service.gpg.ink
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/sider2vf/upptime/master/assets/logo.png
  name: Pigeon SNS Service Health dashboard
  introTitle: "Pigeon SNS is a part of the decentralized social network Mastodon."
  introMessage: 在此页面上，您可观测到 GPG.INK 上的 Mastodon 实例的 实时 运行状况
  navbar:
    - title: SNS
      href: https://gpg.ink/@i
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
